language: cpp
dist: focal

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libpthread-stubs0-dev
  - sudo apt-get install -y libmysqlclient-dev

script:
  - cmake -S . -B build
  - cmake --build build
