name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1

    - name: pthread install
      run: sudo apt-get install -y libpthread-stubs0-dev

    - name: mysqlclient install
      run: sudo apt-get install -y libmysqlclient-dev

    - name: Configure
      run: cmake -S . -B build

    - name: make
      run: cmake --build build
