name: Build

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: pthread install
        run: sudo apt-get install -y libpthread-stubs0-dev

      - name: mysqlclient install
        run: sudo apt-get install -y libmysqlclient-dev

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

